backend:
  name: git-gateway
  branch: master 

media_folder: "public/uploads" 
public_folder: "/uploads" 

collections:
  - name: "home_slides" 
    label: "Home Slides" 
    folder: "src/home_slides" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen de fondo", name: "imagen", widget: "image"}
      - {label: "Subtitulo", name: "subtitle", widget: "string"}
      - {label: "Enlace", name: "url", widget: "string"}